### ISSUE TITLE
witch portal removal segfaults

### ISSUE THREAD

**Issue by bretonium** [bretonium/my-infclass-server#9]
Always reproducible:

1. `inf_experimental_witch 1`
2. Become a witch (for example, with `inf_set_class 0 witch`)
3. Place IN portal, place OUT portal, remove IN portal, remove OUT portal

```
(gdb) where
#0  0x00005555555f7b59 in CPortal::Disconnect (this=0x0) at src/game/server/entities/portal.cpp:73
#1  0x00005555556036b8 in CCharacter::PlacePortal (this=0x5555558e0fe0 <ms_PoolDataCCharacter>) at src/game/server/entities/character.cpp:1467
#2  0x00005555556029ad in CCharacter::FireWeapon (this=0x5555558e0fe0 <ms_PoolDataCCharacter>) at src/game/server/entities/character.cpp:1344
#3  0x0000555555604717 in CCharacter::OnDirectInput (this=0x5555558e0fe0 <ms_PoolDataCCharacter>, pNewInput=0x7ffff2cf3560)
    at src/game/server/entities/character.cpp:1722
#4  0x00005555555d687d in CPlayer::OnDirectInput (this=0x5555558d1440 <ms_PoolDataCPlayer>, NewInput=0x7ffff2cf3560) at src/game/server/player.cpp:462
#5  0x00005555555df18c in CGameContext::OnClientDirectInput (this=0x7ffff7fb0010, ClientID=0, pInput=0x7ffff2cf3560) at src/game/server/gamecontext.cpp:1350
#6  0x00005555555a3e26 in CServer::ProcessClientPacket (this=0x7ffff2cf3010, pPacket=0x7fffffffdb80) at src/engine/server/server.cpp:1353
#7  0x00005555555a5bfa in CServer::PumpNetwork (this=0x7ffff2cf3010) at src/engine/server/server.cpp:1753
#8  0x00005555555a7919 in CServer::Run (this=0x7ffff2cf3010) at src/engine/server/server.cpp:2242
#9  0x00005555555aa803 in main (argc=1, argv=0x7fffffffe018) at src/engine/server/server.cpp:2862
```

**Comment by Kaffeine** [comment]
Fixed. Thanks!
